---

- name: cuda-drivers in NVIDIA APT repository is installed
  apt:
    name: cuda-drivers
    state: present
    install_recommends: no
    update_cache: yes
  when: nvidia_driver_repo == "nvidia"

- name: cuda-drivers in NVIDIA APT repository is removed
  apt:
    name: cuda-drivers
    state: absent
    autoremove: yes
    install_recommends: no
    update_cache: yes
  when: nvidia_driver_repo != "nvidia"

- name: graphics-driver ppa APT repository is registered
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    filename: graphics-driver
    state: present
    mode: 0644
    update_cache: yes
  when: nvidia_driver_repo == "ppa"

- name: NVIDIA graphics driver {{ nvidia_driver_version }} is installed from {{ nvidia_driver_repo }}
  apt:
    name: nvidia-{{ nvidia_driver_version }}
    state: present
    install_recommends: no
    update_cache: yes
  when: nvidia_driver_repo in ["ubuntu", "ppa"]

- name: disable nonveau, opensource version of NVIDIA graphics driver
  lineinfile:
    dest: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="$GRUB_CMDLINE_LINUX_DEFAULT nouveau.modeset=0"'
    validate: 'sh -n %s'
    create: yes
